### ISSUE TITLE
How to render children array?

### ISSUE THREAD

**Issue by dakom** [WebReflection/neverland#10]
Consider this example ([codesandbox](https://codesandbox.io/s/7zkpojv521)):

```
import neverland, {render, html} from "neverland";


const Child = name => neverland(() => {
  return html`
    <div>${name}</div>
  `;
});

const Parent = neverland((children) => {
  return html`
    <div>
     ${children}
    </div>
  `;
});

const App = neverland(() => {
  return html`
    <div>
    ${Parent([
      Child("apple"),
      Child("banana"),
      Child("cherry")
    ])}
    </div>
  `;
})

render(document.getElementById("app"), App);
```

I have a couple questions:

1. What is the correct way to get the children to render? If I replace `${children}` with `${children[1]}` or whatever index, the individual  child does render... but as a list, it doesn't

2. What is the difference between `A` and `B` in `const Foo = A => neverland(B => {...})` - i.e. you can see in the above that `name` is passed as `A` to `Child` but if I simply read it from `B` that would work too.

**Comment by WebReflection** [comment]
You need to stop using 0.5.2 + you need to use `neverland` API, creating components through the neverland function. If you use a function that returns a neverland function you are doing it wrong.

This works as expected once you use latest neverland since 0.5.2 is already jurassic version.

Please don't file any other question with a version that is not the latest, thanks.

```js
import neverland, {render, html} from "neverland";


const Child = neverland((name) => {
  return html`
    <div>${name}</div>
  `;
});

const Parent = neverland((children) => {
  return html`
    <div>
     ${children}
    </div>
  `;
});

const App = neverland(() => {
  return html`
    <div>
    ${Parent([
      Child("apple"),
      Child("banana"),
      Child("cherry")
    ])}
    </div>
  `;
})

render(document.getElementById("app"), App);
```

**Comment by dakom** [comment]
Ah - I think what was also throwing me off was when a component does not require props it still needs to be called... 

e.g., this is correct:
```
${Parent([
      Child(),
      Child(),
      Child()
    ])}
```

*not* this:

```
${Parent([
      Child,
      Child,
      Child
    ])}
```

**Comment by WebReflection** [comment]
which is fine, considering every time you are creating a new component (yet DOM is keyed in neverland).

Although, I might change the tagger to invoke functions automatically when this happens, since I think that what happens anyway when you `${Child}`, although it's important to understand you can have components by reference and be sure it's always the right one.

```js
const {current: children} = useRef(() => [Child(), Child(), Child()]);
const {current: parent} = useRef(() => Parent(children));
return ${parent};
```

But I think that is overly complicated for most common use cases

**Comment by WebReflection** [comment]
btw, current version auto invokes functions, if found inside array, so that the following should work too:

```js
${Parent([
      Child,
      Child,
      Child
])}
```

**Comment by WebReflection** [comment]
by the way, the whole idea is that you define a component, then you create it via:

```js
const child = useRef(Child);
return html`${child}`;
```

A neverland component is basically a wrap of a function that every single time return a new augmented version of such function.

In the `useRef` case you can pass a function so that it'll be invoked only once, avoiding unnecessary GC operations.

In that way you see that having components as functions is better than needing to store somehow, and somewhere, a reference per each instance.

On top of that, the `render` also wants a function, so you can `render(node, App)` and call it a day.

I hope it's now clear why things are done this way.

**Comment by dakom** [comment]
Thanks for the explanation!

I'm still not quite clear on something though..

Can you share a use case of where I want to wrap my neverland components with useRef vs where I don't?

**Comment by WebReflection** [comment]
basically, as it is now, each composed state change will re-create new components.

Using the previous example, this will show in console that the App content changes every second

```js
const {default: $, render, html, useRef, useState} = neverland;

const Child = $((name) => html`
  <div>${name}</div>`
);

const Parent = $((children) => html`
  <div>${children}</div>
`);

const RuntimeApp = $(() => {
  const [i, update] = useState(0);
  setTimeout(update, 1000, i + 1);
  return html`
  <div>
    ${Parent([
      Child("apple"),
      Child("banana"),
      Child("cherry")
    ])}
  </div>
  `;
});

render(document.body, RuntimeApp);
```

However, using the cached version you'll see nothing ever changes on the DOM:
```js
const CachedApp = $(() => {
  const [i, update] = useState(0);
  setTimeout(update, 1000, i + 1);
  const {current: children} = useRef(() => [
    Child("apple"),
    Child("banana"),
    Child("cherry")
  ]);
  const {current: parent} = useRef(() => Parent(children));
  return html`<div>${parent}</div>`;
});

render(document.body, CachedApp);
```

Now the question is, should neverland be that magic that invoking in place the same component will return always the same result? 'cause in such case it needs to hooks itself into the augmentor

**Comment by dakom** [comment]
Oh.... yeah this is tricky..

I think React doesn't affect the dom in this case only because it's doing that calculation in the vdom?

**Comment by dakom** [comment]
Fwiw I don't think it's good from userland to magically cache because then it will create differences compared to React hooks. e.g. local variables _should_ be reset on each render unless you deliberately store them in `useRef` or `useMemo`

**Comment by dakom** [comment]
But then if this approach makes every re-render rewrite the whole tree it'll kill performance - and where does the template diffing even happen?

Please correct me if I'm misunderstanding the situation

**Comment by WebReflection** [comment]
fair enough, so I've changed all the things and now we're really in land of unicorns ...

```js
const {default: $, render, html, useRef, useState} = neverland;

const Child = $((name, i) => html`
  <div>${name} ${i}</div>`
);

const Parent = $((children) => html`
  <div>${children}</div>
`);

const App = $(() => {
  const [i, update] = useState(0);
  setTimeout(update, 1000, i + 1);
  return html`
  <div>
    ${Parent([
      Child("apple", i),
      Child("banana", i),
      Child("cherry", i)
    ])}
  </div>
  `;
});

render(document.body, App);
```

V1 is out FTW 🎉

**Comment by WebReflection** [comment]
### What have I done ?

  * each component is now an augmented function
  * each component creates an augmented version of the passed function, only if not already available in the stack
  * the stack is the execution stack
  * the outer augmentor leans after itself through its own effect
  * each derived instance is magically assigned by reference or new, nobody knows, nobody should care 🎉

As you can see in the [latest children demo](https://webreflection.github.io/neverland/test/children.html) only the text content gets updated.

Holy shit, this `augmentor` actually works 😂

**Comment by dakom** [comment]
That is awesome... so just to confirm I understand things, we now have 3 options for "frameworks with hooks":

1. React

Pros: developed by Facebook so dogfooded by _lots_ of users, and hence likely to have tons of third-party components in the wild and more ability to catch bugs in different scenarios

Cons: unnecessary vdom, comparatively bloated, unnecessary separation of concerns for pure web usage (i.e. "reconciler" that doesn't know about the dom - great for allowing ReactNative, bad for allowing dom-specific optimizations at that level)

2. Haunted

Pros: works with any web-components framework, probably pretty fast if the framework is too

Cons: requires a web-components framework (and that means additional bloat, polyfills, etc. and especially due to the historical problems of polyfilling shadowdom, not great for legacy browsers)

3. Neverland

Pros: Probably the fastest of the bunch, no need to differentiate between "virtual" and "component", builds on the simplicity of pure javascript and string templates (e.g. lighterhtml)

Cons: Only recently out of beta, few people have heard of it (hence it's not as widely tested)

That about right?

**Comment by WebReflection** [comment]
P.S. Haunted is great **but** it uses _Proxy_, which cannot be polyfilled, so between Proxy, Shadow DOM, and Custom Elements, I'd say Haunted is a hazard if Web compatibility is a goal, while it's cool if you target only latest greatest.

**Comment by dakom** [comment]
Hmmm... at a glance of swiss, I like the idea of "choose your framework" but I think that should be abstracted at a higher level...

In other words, it should be done by "hook compositions" authors - and there should be a standard interface in Typescript or whatever. In other words there could be _no dependencies_ burnt in by those hook composition libraries- rather, they accept the dependency as a parameter, then it can be used for all these frameworks without needing to know anything about any of them.

e.g. instead of:

```
import {useState} from "neverland" //or "react" or "haunted" or "swiss"
const myAwesomeHook = () => {
	/*stuff with useState */
}
```

It'd be like (untested, just a first thought):

```
interface IDeps {
  useState: <S>(initialState:S) => [S, (newState:S) => void];
  component?: (fn:() => any) => (() => any)
}

const myAwesomeHook = (deps:IDeps) => {
  const {useState, component} = deps;
  const _hook = () => {
	/*stuff with useState */
  }

  return component ? component(_hook) : _hook;
}
```

Then, as the _app developer_ - say you import it and use it like:

```
//in hooks.js/ts
//this is _slightly_ annoying but really not a big deal at all and could be easily automated
import {myAwesomeHook as _myAwesomeHook} from "thirdParty";
import * as HookDeps from "neverland"; //or react, haunted, swiss, etc.

export const myAwesomeHook = _myAwesomeHook(HookDeps);

//in App
import {myAwesomeHook} from "./hooks"; //notably - not from the third-party lib here
```

Just a thought... but it feels weird that there's all these similarities and potential for generic composition, and it doesn't even relate to semver (i.e. the odds of React changing `useState` is pretty different than changing other parts of the framework that would require a major bump)

I don't think I'm going to do anything about this, and there's nuance to iron out (i.e. how to differentiate between virtual and component for haunted)... but it's food for thought!

**Comment by WebReflection** [comment]
FWIW _lighterhtml_ works like that, it exposes a `hook` method that returns `html` and `svg` template tags to use with whatever libraries is that, including _neverland_ https://github.com/WebReflection/neverland/blob/master/esm/index.js#L11

**Comment by WebReflection** [comment]
FYI, I've cerated a [codepen.md](https://github.com/WebReflection/neverland/blob/master/codepen.md) file

**Comment by dakom** [comment]
Great - I updated the dependencies to just point at https://unpkg.com/neverland

Also gave them clearer descriptions in the html page
