### ISSUE TITLE
useContext usage

### ISSUE THREAD

**Issue by jgoux** [WebReflection/neverland#19]
Hello,

I'm trying neverland and I can't make createContext / useContext works properly.

Here is a codesandbox of what I'm trying to do : https://codesandbox.io/s/mqwr59qw8p

I want to define a theme through a context, and consume it in a component deeper in the tree.

Thanks for your help!

**Comment by felipeegasneris** [comment]
+1 for this please!!!!

**Comment by WebReflection** [comment]
I've updated the current project status https://github.com/WebReflection/neverland/blob/master/README.md#warning

all bugs are likely related to its dependencies anyway, so I am going to close issues in here.

Apologies for any inconvenience.
