### ISSUE TITLE
Persisted State

### ISSUE THREAD

**Issue by lucaseverett** [WebReflection/neverland#20]
After a component is disconnected, it's state is persisted. The next time the component is used, it's prior state still exists.

The behavior in React, and what I was expecting, is for the state to be cleared when the component is disconnected.

In the below examples, I've added a button to toggle the counter example. After hiding the counter button, it's previous count is still there after showing it again.

Neverland Example
https://codesandbox.io/s/0o8m0onvpp

React Example
https://codesandbox.io/s/x9rzqlrrko

**Comment by lucaseverett** [comment]
I understand that these are virtual components, so it's not the same as React.

Is there a way I can clear clear all state when the disconnect effect is invoked?

**Comment by joshgillies** [comment]
Could you create an additional helper hook to manage this? eg.

```js
const useResetableState = (initialState) => {
  const [state, setState] = useState(initialState)
  useEffect(() => () => setState(initialState), [])
  return [state, setState]
}
```

**Comment by lucaseverett** [comment]
Doing it this way seems to work the way I want.

```javascript
function Counter() {
  return component(() => {
    useEffect(() => {
      console.log("connected effect");
      return () => {
        console.log("disconnected effect");
      };
    }, []);
    const [count, setCount] = useState(0);
    return html`
      <button onclick="${() => setCount(count + 1)}">Count: ${count}</button>
    `;
  });
}
```

**Comment by WebReflection** [comment]
@lucaseverett I have errors from raven.js there, not sure what's the issue.

Neverland, or better, dom-augmentor, was born before components became fully stable so I couldn't counter validate expectations.

If React does that I think it'd make sense for dom[augmentor to do the same, since it's goal is to mimic React.

One question though: does react clean the state also when the array of changes to track is **not** empty? 'cause in such case I need to file a bug in augmenter, instead of dom-augmentor (or in both).

Thanks

**Comment by lucaseverett** [comment]
In React, state is cleaned only when the component is unmounted. The difference between having an empty array vs not empty determines if the effect is treated as the componentDidMount or componentWillUnmount lifecycle methods.

**Comment by lucaseverett** [comment]
There's also something strange happening if I use the Counter twice in the Main component. I believe it's related to the same issue, and using the component a second time is using a reference to the existing instance of it, rather than returning a new instance of the component.

```javascript
const Main = component(() => {
  const [show, toggle] = useState(true);
  const [show2, toggle2] = useState(true);
  return html`
    <button onclick="${() => toggle(!show)}">
      ${show ? "Hide" : "Show"}
    </button>
    ${show ? Counter() : undefined}
    
    <br /><br />

    <button onclick="${() => toggle2(!show)}">
      ${show2 ? "Hide" : "Show"}
    </button>
    ${show2 ? Counter() : undefined}
  `;
});
```

**Comment by WebReflection** [comment]
I don't think ternary/partials are supported in React, right?

**Comment by lucaseverett** [comment]
Maybe I misunderstand what you're asking, but in React I often use stateless components with a ternary for conditional rendering.

**Comment by WebReflection** [comment]
I don't think React hooks supports that (or at least it didn't at the beginning)

**Comment by lucaseverett** [comment]
I've only used hooks since the final release. You have to wrap it in a Fragment to return multiple elements, but other than that it works the same as a Class component.

**Comment by lucaseverett** [comment]
Here are some sandboxes using my other example.

Neverland Example
https://codesandbox.io/s/y2l06l579x

React Example
https://codesandbox.io/s/1y79mvy6rl

**Comment by WebReflection** [comment]
I like having examples to look at, but that sandbox thing is not as handy as Code Pen.

Please use Code Pen in the future so it's easy for me to understand what's going on (and it forces you to keep the scope tiny without many files around).

Thanks.

Btw, I'm snowboarding from tomorrow but next week I'll try to fix all the things so please be patience, thanks.

**Comment by WebReflection** [comment]
I've updated the current project status https://github.com/WebReflection/neverland/blob/master/README.md#warning

all bugs are likely related to its dependencies anyway, so I am going to close issues in here.

Apologies for any inconvenience.
