### ISSUE TITLE
Elements won't render after updating state

### ISSUE THREAD

**Issue by nitely** [WebReflection/neverland#21]
The following code will show a text `a`, after clicking the button I expect it to show `a` and `b`. but nothing gets rendered:

```javascript
import stardust, {html, svg, useState} from '//unpkg.com/neverland?module';

const Counter = stardust(() => {
  const [texts, setTexts] = useState(['a']);
  console.log(texts)
  return html`
${texts.map(t => html`<p>${t}</p>`)}

<button onclick=${() => setTexts(['a', 'b'])}>
      Click me
    </button>
  `;
});

document.body.appendChild(Counter());
```

**Comment by yuretz** [comment]
I've tried the latest 0.9.2 lighterhtml with dom-augmentor 0.2.8 and it [has the same issue with array state](https://jsfiddle.net/yuretz/jq7g3y61/). However roughly the same example in pure lighterhtml [works as expected](https://jsfiddle.net/yuretz/dmeor1L7/). Maybe @WebReflection could shed some light on what we are doing wrong, when he has time?

**Comment by WebReflection** [comment]
I'll investigate about the issue but this works for me:

```js
const {default: $, useEffect, useRef, useState} = augmentor;
const {render, html} = lighterhtml;
const Button = (text) => $(() => {
  useEffect(
    () => {
      console.log('connected');
      return () => console.log('disconnected');
    },
    []
  );

  const [items, setItems] = useState([0]);
  return html.for(document)`
  <button onclick=${() => setItems([...items, items.slice(-1)[0] + 1])}>
    ${text}
  </button>
  <div>
  	${items.map((t, i) => html.for(document, i)`<p>${t}</p>`)}
  </div>`;
});

render(document.body, Button('hello'));
```

I think when you have more than a single `html` per component things go banana but it shouldn't

**Comment by yuretz** [comment]
OK, thanks!
BTW, are there also performance benefits in using html.for()? Does it work the same way as Component.for(id) or wire(id) in hyperHTML?

**Comment by nitely** [comment]
btw, it seems neverland is missing the `for` function. I get `TypeError: (intermediate value).for is not a function`.

**Comment by WebReflection** [comment]
Neverland shouldn't expose the `for` function

**Comment by felipeegasneris** [comment]
I have the same issue, there is any solution for array state?

**Comment by WebReflection** [comment]
I've updated the current project status https://github.com/WebReflection/neverland/blob/master/README.md#warning

all bugs are likely related to its dependencies anyway, so I am going to close issues in here.

Apologies for any inconvenience.
