### ISSUE TITLE
useCallback hooks doesn't seem to work the same as in React

### ISSUE THREAD

**Issue by synaptiko** [WebReflection/neverland#24]
While reading documentation about React Hooks I have rewritten [the measure a DOM node example](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node) to neverland but found out it doesn't work, the `height` is always `0`.

Here's the example in neverland: https://codepen.io/anon/pen/vMeLYK

I found the following workaround: https://codepen.io/anon/pen/XQeXJQ

It seems to me that `useCallback` is missing the invocation of memoized function.

**Comment by WebReflection** [comment]
I've updated the current project status https://github.com/WebReflection/neverland/blob/master/README.md#warning

all bugs are likely related to its dependencies anyway, so I am going to close issues in here.

Apologies for any inconvenience.
