### ISSUE TITLE
SSR solution

### ISSUE THREAD

**Issue by jaydenseric** [WebReflection/neverland#25]
Is SSR possible with `neverland`?

I'm trying to work out the best way out of the fleet of packages to achieve hooks and SSR.

Thanks for all your hard work 🙌

**Comment by WebReflection** [comment]
I think hooks and SSR don't really work well together, but since I've recently managed to create [🔥 heresy 🔥 SSR](https://github.com/WebReflection/heresy-ssr) I believe you can use the same dependencies to have neverland on the server too.
