### ISSUE TITLE
rendering array can cause bad ordering of nodes in dom

### ISSUE THREAD

**Issue by asafigan** [WebReflection/neverland#26]
I did a [small test](https://codesandbox.io/s/1y08ov5vzj) and it looks like the array rendering is off. When clicking the "add counter" button multiple times, it should render the "add counter" button at the end but it actually renders after the first counter.

**Comment by WebReflection** [comment]
Your app renders an array of counters then the button

**Comment by asafigan** [comment]
If you click the button multiple times and then look at the dom. The "add counter" button is rendered after the first counter. This is what it should look like: https://codesandbox.io/s/jjvjx598w9. But you see I had to rap the array in a div to get around the bug.

**Comment by WebReflection** [comment]
that's funny, however, if I write the following:

```js
const app = neverland(() => {
  const [counters, updateCounters] = useState(0);

  return html`
    <div>${new Array(counters).fill(0).map(() => counter())}</div>
    <button onclick="${() => updateCounters(counters + 1)}">add counter</button>
  `;
});
```

everything is fine.

this might be a bug for either lighterhtml or dom-augmentor, nothing that can be solved in here, so I'll keep this closed for now.

It'd be nice to have reproducible case that is not based on Neverland (neverlnad just exports things together, it really has little logic involved, and this issue doesn't seem related to it).

Thanks.

**Comment by WebReflection** [comment]
OK, dropping the augmenter part from lighterhtml produces expected results:

```js
const {html, render} = lighterhtml;

const counter = (count, i, array) => {
  return html`
    <div>${count}</div>
    <button onclick=${
      () => {
        array[i]++;
        update(array);
      }
    }>up</button>
  `;
};

const app = (counters) => {
  return html`
    ${counters.map(counter)}
    <button onclick=${() => update(counters.concat(0))}>add counter</button>
  `;
};

function update(counters) {
  render(document.body, () => app(counters));
}

update([]);
```

so, this might be a dom-augmentor related issue indeed.

**Comment by asafigan** [comment]
Ok, thanks for looking into it.
