### ISSUE TITLE
The useEffect method refers to the initial state

### ISSUE THREAD

**Issue by FTOH** [WebReflection/neverland#38]
Live test: https://codepen.io/FTOH/pen/RwwqRLE
```javascript
const {neverland: $, html, useState, useEffect} = neverland

const Counter = $((name) => {
  const [count, setCount] = useState(0);
  
  useEffect(() => {
    console.log(count) // always 0
    const time = setTimeout(setCount, 1000, count + 1)
    return () => clearTimeout(time)
  }, [count])
  
  return html`
  <button onclick=${() => setCount(count + 1)}>
    ${name}: ${count}
  </button>`;
});

document.body.appendChild(Counter('Hit'));
```

React example: https://codepen.io/FTOH/pen/XWWyKza

**Comment by WebReflection** [comment]
this is, unfortunately, a (current) design limitation of neverland, where the hook is related to the first cycle, but it wouldn't work out of that ... the work around would be ugly, so I'll keep this open, but right now I can tell you: don't use intervals with hooks, as these would update only the first time, and never, anything, again.

Since the solution is everything but trivial, I can't provide any estimation, but I can ensure you this would work with heresy, as the node reference is always correct.

**Comment by FTOH** [comment]
React also support Functional updates API for setState
`setCount(prevCount => prevCount + 1)`
It can solve problem in my example

**Comment by WebReflection** [comment]
the title is misleading, as that's not true. If you use states as effects, there is an issue, but there is zero issue if you just click the button with its useState.

> React also support Functional updates API for setState

are you saying if the passed value is a function it invokes it? This might be an easy to solve issue for [augmentor](https://github.com/WebReflection/augmentor).

The other case works with heresy though, maybe you can use that instead, if you need state changes on side-effects?

**Comment by WebReflection** [comment]
Never mind, even heresy doesn't work, so I think this is an _augmentor_ issue.

Will dig a bit more, and eventually open a bug in there 👋

**Comment by WebReflection** [comment]
P.S. I'm on it, it should work soon.

**Comment by WebReflection** [comment]
Yup, all issues solved. [neverland works now](https://codepen.io/WebReflection/pen/YzzRxOy?editors=0010), and [heresy too](https://codepen.io/WebReflection/pen/JjjeJRr), but you can also `setState(callback)` now, and it will pass along the previous state too.

P.S. when you create a pen, never pass the version along, unless you really mean to stick with such version. `https://unpkg.copm/neverland` would be enough 😉
