### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/neverland#43]
Hello. 👋
I've encountered something while experimenting with Neverland. 

This simple example throws an error:
> Cannot read property of 'apply' of undefined
```javascript
import {html, svg, render} from 'https://unpkg.com/neverland?module'
render(document.body, html`<button>Click</button>`);
```
This error occurs in the examples too.
I don't know if I am doing something wrong or missing something.
Thank you for your help. :)

**Comment by WebReflection** [comment]
Fixed, thanks!
