### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/neverland#44]
Hello again.

In this example the Button component won't render.
```javascript
import { html, svg, render} from 'https://unpkg.com/neverland?module';

const Button = (props) => html`<button type="button">${ props.title }</button>`;

render(document.body, html`<div>Click me: ${ Button({ title: 'Click' }) }</div>`);
```
Same goes for the other examples in the README.MD

Thanks for your time. :)

**Comment by WebReflection** [comment]
Oh yeah, I've missed that ... although, if you don't import `neverland` wrapper at all, you're better off with just `lighterhtml`, it would work out of the box in this case (but I'll fix neverlnd too)

**Comment by CaptainJKoB** [comment]
I always test both for the examples just to see if the behaviour was any different.
I am working on a project that uses `neverland`. `lighterhtml` is awesome but i need the power of hooks too.
Imports in the example are just the needed ones to reproduce it, besides the svg.

**Comment by WebReflection** [comment]
Done, thanks!
