### ISSUE TITLE
more info on useContext

### ISSUE THREAD

**Issue by dakom** [WebReflection/neverland#6]
The Readme says: 

> About useContext and useImperativeMethods
> These two hooks are strictly React oriented and have no meaning in current dom-augmentor world.

I'm not really clear on the use case for `useImperativeMethods`, but coming from React I do use Context fairly often...

Do you mind explaining a bit how the problems Context solves are done in Neverland? Just for the sake of clarity - what I mean is having some top-level prop that should cause a re-render of the entire tree, and a deeply nested child that can read that prop, without needing to explicitly pass that prop all the way down.

**Comment by WebReflection** [comment]
let's make this mutually beneficial: can you show me any example of `useContext` hook? 'cause I've found it hard from their documentation to understand what the hell is that about

**Comment by dakom** [comment]
The only full React app I've built which benefited from Context is for work / closed source so I can't share it as a proper example - but I'll try to describe the problem it solved.

Let's say we have a top-level Context called UserData. It contains the avatar url, userId, etc.

Then there's a few _deeply nested_ components that render that UserData - displaying the avatar, calling services with the userId, and so on.

When the UserData is changed, all the components that depend on it must re-render. In React, that means the top level UserData must be passed all the way down to each component. 

It gets super annoying having to literally do things like this on each component just for the sake of passing it down:
```
<Child userData={this.props.userData}>
```

So Context lets you automate that and just wrap the deeply nested child with the context - without having to manually pass the `userData` down through props.

The UserData case might be a bit silly since it's unlikely to be something that is also _changed_ through the nested children - but I'm sure you get the idea. In real-world use case I'm using it to also pass things that are both needed by deeply nested children, and get changed by them.

The example of a "Theme" on the React docs is pretty good - i.e. imagine if we had a sub-sub-component that let you change the color of the current global theme for the app.

**Comment by dakom** [comment]
Sure - I'll try and build a demo... can't get to it this moment but will update here when I do

**Comment by dakom** [comment]
Here - I put together this example... does it help explain the use case?

https://codesandbox.io/s/jjyoor60ov

Imagine that `Login` and/or `UserDisplay` are deeeeeppplyy nested

**Comment by dakom** [comment]
I tried to answer these in the comments in that example, but to hone in on your exact questions:

> Where you define the top most thing?

In the `value` property of the context's [Provider](https://reactjs.org/docs/context.html#contextprovider)

> how is everything updated on top most thing changes?

I think it's conceptually the same idea as passing props down manually. Context is _mostly_ just a helper to avoid that headache. At least that's how I experience and why I reach for it (i.e. if hyper has another solution for that - great!).

However - I think one of the differences is that it doesn't re-render all children - just descendants that are wrapped in a `Consumer`. Not 100% sure about that though.

>  what kind of changes? 

Changing the `value` prop on the `Provider` forces every descendant `Consumer` to re-render.

**Comment by WebReflection** [comment]
so, the key seems to be `<auth_ctx.Provider value={authState}>`, but I need to think about it, and see what I can do.

In any case, this has nothing strictly to do with Neverland, 'cause it's eventually an `augmentor` enhancement, and I've created a ticket for it.

Let's eventually discuss further in there 👋

**Comment by dakom** [comment]
I think it's not exported for Neverland (v1.0.2) even though it was added at https://github.com/WebReflection/augmentor/issues/2

**Comment by WebReflection** [comment]
sorry for that, in @ `v1.0.3`

**Comment by dakom** [comment]
I see `useContext` now but not `createContext`

**Comment by WebReflection** [comment]
that happens when you rush between other tasks ... sorry again, give me a minute

**Comment by WebReflection** [comment]
`v1.0.4` in the house 🍻
