### ISSUE TITLE
Performance vs. React w/ Hooks

### ISSUE THREAD

**Issue by dakom** [WebReflection/neverland#7]
Given that [lighterhtml](https://github.com/WebReflection/lighterhtml) is faster than [hyperHTML](https://github.com/WebReflection/hyperHTML) and hyper is faster than react (right?), I'm curious to see how neverland stacks up against react w/ hooks....

**Comment by WebReflection** [comment]
Then please add a benchmark and file a PR 👍

**Comment by dakom** [comment]
fair point... but filing an issue is _so much easier_ :P 

Just to explain - I thought maybe you already had some benchmarking stuff ready for all the work you've been doing on hyperHTML over the years and it would just be about plugging these new variations in.

No biggie - on paper it seems like it'd be faster anyway

**Comment by WebReflection** [comment]
I have gazillion hyperHTML benchmark but none for the augmentor, however it's a matter of how long it takes to invoke a function and increment an index, so I guess it's pretty fast after all.

If I'll ever find the time to add a benchmark in both libraries I'll ping you back ;-)
